DELETE FROM users WHERE role = 'USER';

CREATE TYPE "Role_new" AS ENUM ('CANDIDATE', 'EMPLOYER', 'ADMIN');

ALTER TABLE users ALTER COLUMN role DROP DEFAULT;

ALTER TABLE users
  ALTER COLUMN role TYPE "Role_new"
  USING (role::text::"Role_new");

DROP TYPE "Role";
ALTER TYPE "Role_new" RENAME TO "Role";

ALTER TABLE users ALTER COLUMN role SET DEFAULT 'CANDIDATE';
